  MyApplicationLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: "MyAppALB"
      Scheme: "internet-facing"
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: "60"
      Subnets:
        - subnet-0326274eb5850abe1
        
      SecurityGroups:
        - !Ref WebServerSecurityGroup

  ALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup1
        - Type: forward
          TargetGroupArn: !Ref TargetGroup2
          Conditions:
            - Field: "host-header"
              Values: 
                - "app1.mydomain.com"
      LoadBalancerArn: !Ref MyApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  TargetGroup1:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckProtocol: HTTP
      HealthCheckPort: 80
      HealthCheckPath: /
      Port: 80
      Protocol: HTTP
      VpcId: "vpc-0123456789abcdef"

  TargetGroup2:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckProtocol: HTTP
      HealthCheckPort: 80
      HealthCheckPath: /
      Port: 80
      Protocol: HTTP
      VpcId: "vpc-0123456789abcdef"
