---
- name: Generate a self-signed SSL certificate
  hosts: webserver
  become: yes
  tasks:
    - name: Install OpenSSL for certificate creation
      apt:
        name: openssl
        state: present

    - name: Create directory for SSL certificates
      file:
        path: /etc/ssl/private
        state: directory
        mode: '0700'

    - name: Generate SSL certificate and private key
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout /etc/ssl/private/selfsigned.key
        -out /etc/ssl/certs/selfsigned.crt
        -subj "/C=US/ST=California/L=SanFrancisco/O=MyCompany/OU=IT/CN=yourdomain.com"  
